version: 2.1

orbs:
  rn: react-native-community/react-native@dev:0.1.0-rc14

jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  install_example:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install example
          command: cd example && rn/yarn_install

  analyse:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Lint JS Code (ESLint)
          command: yarn run lint
      - run:
          name: Flow
          command: yarn run flow
      - run:
          name: Jest
          command: yarn run test

workflows:
  test:
    jobs:
      - checkout_code
      - analyse:
          requires:
            - checkout_code
      - install_example:
          requires:
            - checkout_code
      - rn/android_build:
          project_path: "example/android"
          name: build_android_debug
          requires:
            - install_example

    # Add Detox tests before running this expensive job.
    # - rn/ios_build_and_test:
    #     project_path: "example/ios/example.xcodeproj"
    #     device: "iPhone X"
    #     build_configuration: "Debug"
    #     scheme: "Example"
    #     requires:
    #       - analyse
