version: 2.1

orbs:
  rn: react-native-community/react-native@dev:0.1.0-rc12

jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
  analyse:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Lint JS Code (ESLint)
          command: yarn run lint
      - run:
          name: Flow
          command: yarn run flow
      - run:
          name: Jest
          command: yarn run test

workflows:
  test:
    jobs:
      - checkout_code
      - analyse:
          requires:
            - checkout_code
      - rn/android_build:
          name: build_android_debug
          project_path: "example/android"
          build_type: debug
          requires:
            - analyse
      - rn/ios_build:
          project_path: "example/ios/Example.xcodeproj"
          device: "iPhone X"
          build_configuration: "Debug"
          scheme: "Example"
          requires:
            - analyse
